spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gamedemodb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:9991509}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

app:
  feature:
    enable-websocket: true
    enable-redis-cache: true
    enable-rabbitmq: true
    max-game-rooms: 500
    max-players-per-room: 8

logging:
  level:
    org.springframework.security: WARN
    com.emrearcnn.gamedemo: INFO 